// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: dispatch.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 晶圓批次請求
type LotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LotId         string                 `protobuf:"bytes,1,opt,name=lot_id,json=lotId,proto3" json:"lot_id,omitempty"`                   // 晶圓批次 ID (例如: LOT-20260715-01)
	ProcessType   string                 `protobuf:"bytes,2,opt,name=process_type,json=processType,proto3" json:"process_type,omitempty"` // 需要的工序 (例如: LITHOGRAPHY, ETCHING)
	DueDate       int64                  `protobuf:"varint,3,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`            // 交期時間戳 (EDD 演算法會用到)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LotRequest) Reset() {
	*x = LotRequest{}
	mi := &file_dispatch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LotRequest) ProtoMessage() {}

func (x *LotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dispatch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LotRequest.ProtoReflect.Descriptor instead.
func (*LotRequest) Descriptor() ([]byte, []int) {
	return file_dispatch_proto_rawDescGZIP(), []int{0}
}

func (x *LotRequest) GetLotId() string {
	if x != nil {
		return x.LotId
	}
	return ""
}

func (x *LotRequest) GetProcessType() string {
	if x != nil {
		return x.ProcessType
	}
	return ""
}

func (x *LotRequest) GetDueDate() int64 {
	if x != nil {
		return x.DueDate
	}
	return 0
}

// 派工決策結果
type DispatchResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LotId             string                 `protobuf:"bytes,1,opt,name=lot_id,json=lotId,proto3" json:"lot_id,omitempty"`
	AssignedMachineId string                 `protobuf:"bytes,2,opt,name=assigned_machine_id,json=assignedMachineId,proto3" json:"assigned_machine_id,omitempty"` // 被指派的機台 ID
	Status            string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                                                  // 派工結果狀態 (SUCCESS / FAILED_NO_MACHINE)
	DispatchedAt      int64                  `protobuf:"varint,4,opt,name=dispatched_at,json=dispatchedAt,proto3" json:"dispatched_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DispatchResponse) Reset() {
	*x = DispatchResponse{}
	mi := &file_dispatch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchResponse) ProtoMessage() {}

func (x *DispatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dispatch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchResponse.ProtoReflect.Descriptor instead.
func (*DispatchResponse) Descriptor() ([]byte, []int) {
	return file_dispatch_proto_rawDescGZIP(), []int{1}
}

func (x *DispatchResponse) GetLotId() string {
	if x != nil {
		return x.LotId
	}
	return ""
}

func (x *DispatchResponse) GetAssignedMachineId() string {
	if x != nil {
		return x.AssignedMachineId
	}
	return ""
}

func (x *DispatchResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DispatchResponse) GetDispatchedAt() int64 {
	if x != nil {
		return x.DispatchedAt
	}
	return 0
}

var File_dispatch_proto protoreflect.FileDescriptor

const file_dispatch_proto_rawDesc = "" +
	"\n" +
	"\x0edispatch.proto\x12\bdispatch\"a\n" +
	"\n" +
	"LotRequest\x12\x15\n" +
	"\x06lot_id\x18\x01 \x01(\tR\x05lotId\x12!\n" +
	"\fprocess_type\x18\x02 \x01(\tR\vprocessType\x12\x19\n" +
	"\bdue_date\x18\x03 \x01(\x03R\adueDate\"\x96\x01\n" +
	"\x10DispatchResponse\x12\x15\n" +
	"\x06lot_id\x18\x01 \x01(\tR\x05lotId\x12.\n" +
	"\x13assigned_machine_id\x18\x02 \x01(\tR\x11assignedMachineId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12#\n" +
	"\rdispatched_at\x18\x04 \x01(\x03R\fdispatchedAt2R\n" +
	"\x0fDispatchService\x12?\n" +
	"\vDispatchLot\x12\x14.dispatch.LotRequest\x1a\x1a.dispatch.DispatchResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_dispatch_proto_rawDescOnce sync.Once
	file_dispatch_proto_rawDescData []byte
)

func file_dispatch_proto_rawDescGZIP() []byte {
	file_dispatch_proto_rawDescOnce.Do(func() {
		file_dispatch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dispatch_proto_rawDesc), len(file_dispatch_proto_rawDesc)))
	})
	return file_dispatch_proto_rawDescData
}

var file_dispatch_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dispatch_proto_goTypes = []any{
	(*LotRequest)(nil),       // 0: dispatch.LotRequest
	(*DispatchResponse)(nil), // 1: dispatch.DispatchResponse
}
var file_dispatch_proto_depIdxs = []int32{
	0, // 0: dispatch.DispatchService.DispatchLot:input_type -> dispatch.LotRequest
	1, // 1: dispatch.DispatchService.DispatchLot:output_type -> dispatch.DispatchResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dispatch_proto_init() }
func file_dispatch_proto_init() {
	if File_dispatch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dispatch_proto_rawDesc), len(file_dispatch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dispatch_proto_goTypes,
		DependencyIndexes: file_dispatch_proto_depIdxs,
		MessageInfos:      file_dispatch_proto_msgTypes,
	}.Build()
	File_dispatch_proto = out.File
	file_dispatch_proto_goTypes = nil
	file_dispatch_proto_depIdxs = nil
}
